info:
  component: Edge Service (Zuul Proxy)


# Default (Local) configuration
spring:
  application:
    name: edge-server
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 3000
        multiplier: 1.3
        max-interval: 5000
        max-attempts: 20
      discovery:
        service-id: config-server
        enabled: false
      uri: http://localhost:8888

zuul:
  semaphore:
    max-semaphores: 2000

# Docker containers deployment configurations         
---
spring:
  profiles: docker
  cloud:
    config:
      uri: http://config-server:8888