version: '2'

services:
  config-server:
    build: ../config-server
    image: demo/config-server
    ports:
      - 8888:8888
    restart: always
    
  patient-service:
    build: ../demo
    image: demo/patient-service
    ports:
      - 8080:8080
    restart: always