version: '2'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: movie
    volumes:
    - /opt/mysql-data:/var/lib/mysql
  adminer:
    image: adminer
    ports:
    - 8081:8080